### ISSUE TITLE
Other log types

### ISSUE THREAD

**Issue by sr71684** [yhisaki/wandb-cpp#1]
Hello,

Epic library. 

Is it possible to support other log metrics, such as video and 3d plots?

**Comment by yhisaki** [comment]
Thank you for your interest in wandb-cpp.

Firstly, supporting 3D plots is challenging . This is because even the main wandb platform doesn't implement comprehensive features for this. However, I have already implemented a feature to output logs compatible with wandb's Object3D. This functionality allows you to plot 3D point clouds and boxes. For more details, please see:
https://github.com/yhisaki/wandb-cpp?tab=readme-ov-file#wandbobject3d

Next, supporting video is possible, but it is not currently implemented. I hope to add this feature soon using https://docs.wandb.ai/ref/python/data-types/video.

As an alternative to these features, you can use https://github.com/yhisaki/wandb-cpp?tab=readme-ov-file#save-file. This allows you to save any files.

**Comment by yhisaki** [comment]
We have added support for video upload functionality! For more details, please see [here](https://github.com/yhisaki/wandb-cpp?tab=readme-ov-file#upload-video)!

**Comment by sr71684** [comment]
so good
